### ISSUE TITLE
Data load fails with "integer out of range"

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#141]
https://github.com/ThreeSixtyGiving/insights-ng/blob/live/insights/db.py#L32 gets translated by sqlalchemy as an `int4 ` in the database schema.

Which according to the docs:
integer | 4 bytes | typical choice for integer | -2147483648 to +2147483647
-- | -- | -- | --

However this isn't large enough to hold a grant amount of £5086000000.0 as seen in 'grant_id': '360G-cabinetoffice-G2-GA-202109475202-20-21'

Resolution - We will need to update this to a `big int`.

```
Processing rows  [####--------------------------------]  89999/720070  00:23:04
10,000 rows to save

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.heroku/python/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 440, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 440, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/app/insights/commands/fetch_data.py", line 261, in fetch_data
    objects = save_objects(objects)
  File "/app/insights/commands/fetch_data.py", line 241, in save_objects
    db.session.bulk_insert_mappings(Grant, objects)
  File "<string>", line 2, in bulk_insert_mappings
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3624, in bulk_insert_mappings
    self._bulk_save_mappings(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3723, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3711, in _bulk_save_mappings
    persistence._bulk_insert(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 104, in _bulk_insert
    _emit_insert_statements(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1094, in _emit_insert_state
ments
    c = connection._execute_20(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception   
    util.raise_(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range

[SQL: INSERT INTO "grant" (dataset, grant_id, title, description, currency, "amountAwarded", "awardDate", "recipientOrganization_id", "recipientOrganization_name", "recipientOrganization_postalCode", "fundingOrganization_id", "fundingOrganization_name", "grantProgramme_title", source_file_id, publisher_id, insights_geo_region, insights_geo_la, insights_geo_country, insights_geo_lat, insights_geo_long, insights_geo_source, insights_org_id, insights_org_id_int, insights_org_type, insights_funding_org_type, insights_band_amount) VALUES (%(dataset)s, %(grant_id)s, %(title)s, %(description)s, %(currency)s, %(amountAwarded)s, %(awardDate)s, %(recipientOrganization_id)s, %(recipientOrganization_name)s, %(recipientOrganization_postalCode)s, %(fundingOrganization_id)s, %(fundingOrganization_name)s, %(grantProgramme_title)s, %(source_file_id)s, %(publisher_id)s, %(insights_geo_region)s, %(insights_geo_la)s, %(insights_geo_country)s, %(insights_geo_lat)s, %(insights_geo_long)s, %(insights_geo_source)s, %(insights_org_id)s, %(insights_org_id_int)s, %(insights_org_type)s, %(insights_funding_org_type)s, %(insights_band_amount)s) RETURNING "grant".id]
[parameters: {'dataset': 'main', 'grant_id': '360G-cabinetoffice-G2-GA-202109475202-20-21', 'title': 'NDA grant contribution 2020-21', 'description': 'To support the NDA meet its responsibilities', 'currency': 'GBP', 'amountAwarded': 5086000000.0, 'awardDate': datetime.date(2020, 4, 1), 'recipientOrganization_id': '360G-cabinetoffice-0012400000MNliQAAT', 'recipientOrganization_name': 'Nuclear Decommissioning Authority', 'recipientOrganization_postalCode': 'CA243HU', 'fundingOrganization_id': 'GB-GOR-D1198', 'fundingOrganization_name': 'Department for Business, Energy and Industrial Strategy', 'grantProgramme_title': 'Nuclear Liabilities Fund grant contribution 20-21', 'source_file_id': 'a003W000004t8ujQAA', 'publisher_id': '360G-cabinetoffice', 'insights_geo_region': 'E12000002', 'insights_geo_la': 'E07000029', 'insights_geo_country': 'E92000001', 'insights_geo_lat': 54.51283154952682, 'insights_geo_long': -3.539972501491694, 'insights_geo_source': 'recipientOrganizationPostcode', 'insights_org_id': '360G-cabinetoffice-0012400000MNliQAAT', 'insights_org_id_int': 292002, 'insights_org_type': 'Identifier not recognised', 'insights_funding_org_type': 'Central Government', 'insights_band_amount': 'Over £1m'}]
```

**Comment by drkane** [comment]
Might be worth doing the same to org_latest_income too - there currently aren't charities with £2bn+ income but it's not inconceivable: https://github.com/ThreeSixtyGiving/insights-ng/blob/live/insights/db.py#L69

**Comment by michaelwood** [comment]
Good idea, have added that to #142
